version: '3.3'
services:
  db:
    container_name: 'currency_database_container'
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_DATABASE: 'currency_database'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'db_password'
    ports:
      - '127.0.0.1:3306:3306'
    expose:
      - '3306'